"""add character skills

Revision ID: 189fcbd34f55
Revises: b2bfa03107ee
Create Date: 2026-09-06 20:09:10.029027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189fcbd34f55'
down_revision: Union[str, Sequence[str], None] = 'b2bfa03107ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_skills_character_id'), 'character_skills', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_skills_id'), 'character_skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_skills_id'), table_name='character_skills')
    op.drop_index(op.f('ix_character_skills_character_id'), table_name='character_skills')
    op.drop_table('character_skills')
    # ### end Alembic commands ###
