"""add character attributes

Revision ID: 687f4278d96d
Revises: 189fcbd34f55
Create Date: 2026-09-06 20:14:58.636437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687f4278d96d'
down_revision: Union[str, Sequence[str], None] = '189fcbd34f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_attributes_character_id'), 'character_attributes', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_attributes_id'), 'character_attributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_attributes_id'), table_name='character_attributes')
    op.drop_index(op.f('ix_character_attributes_character_id'), table_name='character_attributes')
    op.drop_table('character_attributes')
    # ### end Alembic commands ###
