"""add character resources

Revision ID: fd9935f9bd48
Revises: 687f4278d96d
Create Date: 2026-09-06 20:22:50.664909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9935f9bd48'
down_revision: Union[str, Sequence[str], None] = '687f4278d96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_resources_character_id'), 'character_resources', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_resources_id'), 'character_resources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_resources_id'), table_name='character_resources')
    op.drop_index(op.f('ix_character_resources_character_id'), table_name='character_resources')
    op.drop_table('character_resources')
    # ### end Alembic commands ###
